server:
  port: 8883

spring:
  application:
    name: gassman-mail-service
  rabbitmq:
    addresses: amqp://***
  cloud:
    stream:
      bindings:
        userRegistrationChannel:
          destination: gassman-user-registration
        userOrderChannel:
          destination: gassman-order-registration
        orderPaymentConfirmationChannel:
          destination: gassman-order-payment-confirmation
        rechargeUserCreditChannel:
          destination: gassman-recharge-user-credit

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

template:
  registration: "Benvenuto del sistema GasSMan\nLa tua iscrizione e' stata correttamente effettuata con i seguenti dati : \nCognome: %s\nNome: %s\nMail: %s\n\nGrazie\nGasSMan Administrator"
  order: "Ciao %s,\nIl tuo ordine e' stato registrato con successo.\n\nDettaglio dell'ordine:\n%s\n\nTotale ordine : %s\n\nSe vuoi pagare con il tuo credito GasSMan clicca sul link che segue:\n%s\n\nSe vuoi pagare con PayPal clicca sul link che segue:\n%s\n\nGrazie\nGasSMan Administrator"
  paymentPayPalURL: "http://localhost:8881/gassman-payment-service/paypal/make/payment?%s"
  paymentInternalCreditURL: "http://localhost:8881/gassman-payment-service/internal-credit/make/payment?%s"
  paymentConfirmation: "Ciao %s,\nIl tuo pagamento e' stato registrato con successo.\n\nDettaglio dell'ordine pagato:\n%s\n\nTotale ordine : %s\n\nGrazie\nGasSMan Administrator"
  creditrechargeConfirmation: "Ciao %s,\nIl tuo credito e' stato aggiornato:\nCredito precedente  %s euro\nCredito attuale: %s euro\nData e ora dell'aggiornamento: %s\n\nGrazie\nGasSMan Administrator"
  subject:
    registration: "GasSMan - Registrazione nuovo utente"
    order: "GasSMan - Conferma nuovo ordine"
    payment: "GasSMan - Conferma pagamento"
    creditrecharge: "GasSMan - Aggiornamento del credito"

mail:
  host: smtp.yourserver.org
  port:
  username:
  password:

  transport:
    protocol: smtp

  smtp:
    auth: true
    starttls:
      enable: true